ci:
  autofix_prs: false

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.7
    hooks:
      - id: ruff
        args: ["--fix", "--output-format=full"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        files: ^pymc_marketing/
        additional_dependencies: [numpy>=1.20, pandas-stubs]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
    - id: nbqa-ruff
      args: ["--fix", "--output-format=full"]
      files: ^docs/source/notebooks/
      exclude: ^docs/source/notebooks/clv/dev/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: debug-statements
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        exclude: ^docs/source/notebooks/
